"""added sentiment field to Contact

Revision ID: 74cba8f1e465
Revises: cb1a97757008
Create Date: 2026-06-22 06:30:15.336833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cba8f1e465'
down_revision: Union[str, Sequence[str], None] = 'cb1a97757008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('sentiment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'sentiment')
    # ### end Alembic commands ###
