"""added sentiment_source field to Contact

Revision ID: d255aeb198a4
Revises: 74cba8f1e465
Create Date: 2026-06-22 06:50:51.430429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd255aeb198a4'
down_revision: Union[str, Sequence[str], None] = '74cba8f1e465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('sentiment_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'sentiment_source')
    # ### end Alembic commands ###
